[package]
name = "factorio-daemon"
version = "0.1.0"
edition = "2021"

[dependencies]
factorio-api = { path = "../factorio-api" }
factorio-config = { path = "../factorio-config" }
systemd-directories = "0.1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
