name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version'
        required: true

jobs:
  build:
    if: github.repository == 'asasine/factoriod'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3

    - name: Create debian package
      run: |
        echo "Not implemented yet"
        exit 1

    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v5
      with:
        gpg_private_key: ${{ secrets.GPG_SIGNING_KEY }}
        passphrase: ${{ secrets.GPG_SIGNING_KEY_PASSWORD }}
        git_user_signingkey: true
        git_commit_gpgsign: true

    - name: Update packages and sign
      working-directory: docs
      run: |
        dpkg-scanpackages --multiversion . > Packages && gzip -k -f Packages
        apt-ftparchive release . > Release
        gpg --batch --yes --armor --detach-sign --output Release.gpg Release
        gpg --batch --yes --clearsign --output InRelease Release
        git add .

    - name: Commit and push changes
      run: |
        git commit -m "Updated version to ${{ inputs.version }}"
        git push

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        name: v${{ inputs.version }}
        tag_name: v${{ inputs.version }}
        draft: true
        generate_release_notes: true
        files: |
          docs/factoriod.${{ inputs.version }}.deb
